SOURCES = [
  {
    title: "Beyond Good and Evil",
    url: "http://gutenberg.pglaf.org/4/3/6/4363/4363.txt",
    headers: [/^PREFACE$/, /^CHAPTER I. PREJUDICES OF PHILOSOPHERS$/],
    footers: [/^End of Project Gutenberg's Beyond Good and Evil/],
    encoding: Encoding::ASCII_8BIT,
  },
  {
    title: "Thus Spake Zarathustra",
    url: "http://gutenberg.pglaf.org/1/9/9/1998/1998.txt",
    headers: [/^THUS SPAKE ZARATHUSTRA.$/, /^FIRST PART. ZARATHUSTRA'S DISCOURSES.$/],
    footers: [/^APPENDIX.$/],
    encoding: Encoding::ASCII_8BIT,
  },
  {
    title: "The Antichrist",
    url: "http://gutenberg.pglaf.org/1/9/3/2/19322/19322-8.txt",
    headers: [/^PREFACE$/, /^\s+FRIEDRICH W. NIETZSCHE.$/, /^THE ANTICHRIST$/],
    footers: [/^THE END$/],
    encoding: Encoding::ISO_8859_1,
  },
  {
    title: "Human, All Too Human",
    url: "http://gutenberg.pglaf.org/3/8/1/4/38145/38145-8.txt",
    headers: [/^PREFACE.$/, /^OF THE FIRST AND LAST THINGS.$/],
    footers: [/^End of Project Gutenberg's Human, All Too Human/],
    encoding: Encoding::ISO_8859_1,
  },
  {
    title: "Human, All-Too-Human, Part II",
    url: "http://gutenberg.pglaf.org/3/7/8/4/37841/37841-0.txt",
    headers: [/^PART I. MISCELLANEOUS MAXIMS AND OPINIONS.$/],
    footers: [/^\s+‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐‐/, /^FOOTNOTES$/],
    encoding: Encoding::UTF_8,
  },
  {
    title: "The Case Of Wagner",
    url: "http://gutenberg.pglaf.org/2/5/0/1/25012/25012-0.txt",
    headers: [/^THE CASE OF WAGNER: A MUSICIAN’S PROBLEM$/, /^Preface$/],
    footers: [/^FOOTNOTES$/],
    encoding: Encoding::UTF_8,
  },
  {
    title: "The Dawn of Day",
    url: "http://gutenberg.pglaf.org/3/9/9/5/39955/39955-0.txt",
    headers: [/^AUTHOR’S PREFACE.$/, /^BOOK I.$/],
    footers: [/^FOOTNOTES$/],
    encoding: Encoding::UTF_8,
  },
  {
    title: "We Philologists",
    url: "http://gutenberg.pglaf.org/1/8/2/6/18267/18267-8.txt",
    headers: [/^LONDON, _July 1911_.$/],
    footers: [/^FOOTNOTES:$/],
    encoding: Encoding::ISO_8859_1,
  },
]
